### PR TITLE
fix(log): avoid crashing on bad payload

### LINKED ISSUE #410: Check for valid payload when logging.
See this line: https://github.com/mozilla/fxa-oauth-server/blob/master/lib/logging/summary.js#L29

`payload` is possible not an object and will crash the logging code.

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #410

### CODE REVIEW

**Comment by vladikoff** [comment]
@jrgm please r?

**Comment by vladikoff** [comment]
@jrgm we already have a check for `undefined` or `null` payload so it's probably something that cause then, that's why this uses a `try`

File: lib/logging/summary.js [hunk 1]
```diff
@@ -17,6 +18,15 @@ module.exports = function summary(request, response) {
     scope: request.auth.credentials.scope
   };
 
+  var payloadKeys = [];
+  try {
+    // given payload object might not be a valid object
+    // See issue #410
+    payloadKeys = Object.keys(payload);
+  } catch (e) {
+    // failed to parse payload keys.
```
Comment (rfk) [inline lib/logging/summary.js]: I wonder if it's worth adding some sort of sentinel value, like `payloadKeys = ['INVALID_PAYLOAD_OBJECT']` or similar, so that we can easily identify any such cases in the logs.

Comment (vladikoff) [inline lib/logging/summary.js]: yeah!

Comment (jrgm) [inline lib/logging/summary.js]: Small suggestion. Factor the try/catch into a helper function. Otherwise v8 will not optimize the exported function.

**Comment by jrgm** [comment]
Otherwise, plus my suggestion, and @rfk's suggestion, r+ from me.
